# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160512164014 on 2016-06-07 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('dest', models.CharField(blank=True, max_length=50, null=True)),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('jitter', models.IntegerField(blank=True, null=True)),
                ('band', models.FloatField(blank=True, null=True)),
                ('packetloss', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
