# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160512164014 on 2016-06-07 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='testsim2',
        ),
    ]
