# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0003_capture_capturemodel_eventmodel_filemodel_onemodel_results_searchmodel_simulatemodel_test10'),
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
        migrations.RemoveField(
            model_name='testsim2',
            name='dest',
        ),
        migrations.AddField(
            model_name='testsim2',
            name='character',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='testsim2',
            name='pc_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
