# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0004_auto_20160613_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsim2',
            name='dest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
