# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0006_monicaldown1_monicalup1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='results',
        ),
        migrations.DeleteModel(
            name='test10',
        ),
    ]
