# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0007_auto_20160617_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitable',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('ips', models.CharField(blank=True, max_length=50, null=True)),
                ('ipd', models.CharField(blank=True, max_length=50, null=True)),
                ('totalpacketsup', models.IntegerField(blank=True, null=True)),
                ('totalpacketsdown', models.IntegerField(null=True)),
                ('totalpackets', models.IntegerField(null=True)),
                ('sumup', models.IntegerField(blank=True, null=True)),
                ('meanup', models.FloatField(blank=True, null=True)),
                ('bandup', models.CharField(blank=True, max_length=50, null=True)),
                ('sumdown', models.IntegerField(blank=True, null=True)),
                ('meandown', models.FloatField(blank=True, null=True)),
                ('banddown', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
