# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0008_monitable'),
    ]

    operations = [
        migrations.CreateModel(
            name='mdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mip', models.CharField(blank=True, max_length=50, null=True)),
                ('mtime', models.IntegerField()),
                ('mtotal_pkt', models.IntegerField()),
                ('sumup', models.IntegerField(blank=True, null=True)),
                ('sumdown', models.IntegerField(blank=True, null=True)),
                ('meanup', models.FloatField(blank=True, null=True)),
                ('meandown', models.FloatField(blank=True, null=True)),
                ('avg_u_s', models.FloatField(blank=True, null=True)),
                ('avg_d_s', models.FloatField(blank=True, null=True)),
                ('bandup', models.CharField(blank=True, max_length=50, null=True)),
                ('banddown', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'mdetails',
            },
        ),
    ]
