# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0009_mdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitable',
            old_name='date',
            new_name='dates',
        ),
    ]
