# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0010_auto_20160618_0353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monitable',
        ),
    ]
