# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0012_monitable'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitable',
            name='monid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
