# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0013_monitable_monid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitable',
            name='monid',
        ),
    ]
