# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0016_auto_20160621_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='capture',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.DateField(blank=True, null=True)),
                ('ips', models.CharField(blank=True, max_length=50, null=True)),
                ('ipd', models.CharField(blank=True, max_length=50, null=True)),
                ('sum1', models.IntegerField(blank=True, null=True)),
                ('sum2', models.IntegerField(blank=True, null=True)),
                ('mean1', models.FloatField(blank=True, null=True)),
                ('mean2', models.FloatField(blank=True, null=True)),
                ('bandup', models.CharField(blank=True, max_length=50, null=True)),
                ('banddown', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='monitable',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('monid', models.CharField(blank=True, max_length=200, null=True)),
                ('pcid', models.CharField(blank=True, max_length=200, null=True)),
                ('dates', models.DateField(blank=True, null=True)),
                ('ips', models.CharField(blank=True, max_length=50, null=True)),
                ('ipd', models.CharField(blank=True, max_length=50, null=True)),
                ('totalpacketsup', models.IntegerField(blank=True, null=True)),
                ('totalpacketsdown', models.IntegerField(null=True)),
                ('totalpackets', models.IntegerField(null=True)),
                ('sumup', models.IntegerField(blank=True, null=True)),
                ('meanup', models.FloatField(blank=True, null=True)),
                ('bandup', models.CharField(blank=True, max_length=50, null=True)),
                ('sumdown', models.IntegerField(blank=True, null=True)),
                ('meandown', models.FloatField(blank=True, null=True)),
                ('banddown', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='percentageofpacketdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monid1', models.CharField(blank=True, max_length=200, null=True)),
                ('pcid', models.CharField(blank=True, max_length=200, null=True)),
                ('ips1', models.CharField(blank=True, max_length=50, null=True)),
                ('p1_p500', models.IntegerField(blank=True, null=True)),
                ('p501_p1000', models.IntegerField(blank=True, null=True)),
                ('p1001_p2000', models.IntegerField(blank=True, null=True)),
                ('p2001', models.IntegerField(blank=True, null=True)),
                ('totdown', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='percentageofpacketup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monid1', models.CharField(blank=True, max_length=200, null=True)),
                ('pcid', models.CharField(blank=True, max_length=200, null=True)),
                ('ips1', models.CharField(blank=True, max_length=50, null=True)),
                ('p1_p500', models.IntegerField(blank=True, null=True)),
                ('p501_p1000', models.IntegerField(blank=True, null=True)),
                ('p1001_p2000', models.IntegerField(blank=True, null=True)),
                ('p2001', models.IntegerField(blank=True, null=True)),
                ('totup', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
