# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0017_capture_monitable_percentageofpacketdown_percentageofpacketup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='percentageofpacketdown',
        ),
        migrations.DeleteModel(
            name='percentageofpacketup',
        ),
    ]
