# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0019_percentageofpacketdown_percentageofpacketup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monitable',
        ),
        migrations.DeleteModel(
            name='testsim2',
        ),
    ]
