# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0020_auto_20160623_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='monitable',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('simid', models.CharField(blank=True, max_length=200, null=True)),
                ('monid', models.CharField(blank=True, max_length=200, null=True)),
                ('pcid', models.CharField(blank=True, max_length=200, null=True)),
                ('dates', models.DateField(blank=True, null=True)),
                ('ips', models.CharField(blank=True, max_length=50, null=True)),
                ('ipd', models.CharField(blank=True, max_length=50, null=True)),
                ('totalpacketsup', models.IntegerField(blank=True, null=True)),
                ('totalpacketsdown', models.IntegerField(null=True)),
                ('totalpackets', models.IntegerField(null=True)),
                ('sumup', models.IntegerField(blank=True, null=True)),
                ('meanup', models.FloatField(blank=True, null=True)),
                ('bandup', models.CharField(blank=True, max_length=50, null=True)),
                ('sumdown', models.IntegerField(blank=True, null=True)),
                ('meandown', models.FloatField(blank=True, null=True)),
                ('banddown', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='testsim2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simid', models.CharField(blank=True, max_length=50, null=True)),
                ('dest', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('pc_name', models.CharField(blank=True, max_length=30, null=True)),
                ('delay', models.IntegerField(blank=True, null=True)),
                ('jitter', models.IntegerField(blank=True, null=True)),
                ('packetloss', models.FloatField(blank=True, null=True)),
                ('band', models.FloatField(blank=True, null=True)),
                ('character', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
