# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettest', '0021_monitable_testsim2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mdetails',
        ),
        migrations.AddField(
            model_name='host',
            name='opsystem',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='processor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
